
package practicoaulico2.igu;

import java.awt.BorderLayout;
import javax.swing.JDesktopPane;

/**
 *
 * @author marus
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setSize(900, 500);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setTitle("Login");
       
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmEmpresa = new javax.swing.JMenu();
        jmiCargarEmpresa = new javax.swing.JMenuItem();
        jmiConsulta = new javax.swing.JMenuItem();
        jmEmpleado = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicoaulico2/imagenes/6398-vectoriales.jpg"))); // NOI18N
        jlFondo.setMaximumSize(new java.awt.Dimension(1500, 700));
        jlFondo.setMinimumSize(new java.awt.Dimension(1000, 500));
        jlFondo.setPreferredSize(new java.awt.Dimension(1200, 500));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmEmpresa.setBackground(new java.awt.Color(102, 102, 255));
        jmEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmEmpresa.setForeground(new java.awt.Color(0, 51, 255));
        jmEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicoaulico2/imagenes/reportes.png"))); // NOI18N
        jmEmpresa.setText("EMPRESA");
        jmEmpresa.setPreferredSize(new java.awt.Dimension(150, 50));

        jmiCargarEmpresa.setText("CARGAR EMPRESA");
        jmiCargarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCargarEmpresaActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmiCargarEmpresa);

        jmiConsulta.setText("CONSULTA");
        jmEmpresa.add(jmiConsulta);

        jMenuBar1.add(jmEmpresa);

        jmEmpleado.setBackground(new java.awt.Color(102, 102, 255));
        jmEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmEmpleado.setForeground(new java.awt.Color(0, 51, 255));
        jmEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicoaulico2/imagenes/usuario.png"))); // NOI18N
        jmEmpleado.setText("EMPLEADO");
        jmEmpleado.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem1.setText("CARGAR EMPLEADO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmEmpleado.add(jMenuItem1);

        jMenuBar1.add(jmEmpleado);

        jmExit.setBackground(new java.awt.Color(102, 102, 255));
        jmExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmExit.setForeground(new java.awt.Color(0, 51, 255));
        jmExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicoaulico2/imagenes/cerrar-sesion.png"))); // NOI18N
        jmExit.setText("EXIT");
        jmExit.setPreferredSize(new java.awt.Dimension(150, 50));
        jMenuBar1.add(jmExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCargarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarEmpresaActionPerformed
        Empresa nuevo = new Empresa();
        nuevo.setVisible(true);
    }//GEN-LAST:event_jmiCargarEmpresaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Empleado nuevoEmpleado = new Empleado();
        nuevoEmpleado.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JMenu jmEmpleado;
    private javax.swing.JMenu jmEmpresa;
    private javax.swing.JMenu jmExit;
    private javax.swing.JMenuItem jmiCargarEmpresa;
    private javax.swing.JMenuItem jmiConsulta;
    // End of variables declaration//GEN-END:variables
}
